theme: jekyll-theme-minimal

title: Alex Chang
logo: "/images/alexchang.jpeg?>raw=true"
# description: > # your text below (remove <br> elements if you don't need line breaks)
#   Hi! I'm a senior at UC Berkeley studying Computer Science and Linguistics.
#   <br><br>
#   Let's connect!
#   <br><br>
#   <a href="https://www.linkedin.com/in/alex-y-chang/">Linkedin</a>
#   <a href="https://github.com/alexychang">Github</a>
  
